version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  pg_db:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/:/data/postgres
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 81
    ports:
      - 15432:81
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg_db
    networks:
      - main

  mongo_db:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - main

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/pipedrive-bling-integration-api
    depends_on:
      - mongo_db
    networks:
      - main

  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/pipedrive-bling-integration-api
    restart: always
    command: bash -c "yarn && yarn start"
    volumes:
      - ./dist/:/usr/src/pipedrive-bling-integration-api/dist
      - ./package.json:/usr/src/pipedrive-bling-integration-api/package.json
      - ./yarn.lock:/usr/src/pipedrive-bling-integration-api/yarn.lock
    ports:
      - 3032:3032
    depends_on:
      - pg_db
      - mongo_db
      - mongo-express
      - pgadmin
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pgadmin:
  postgres-data:
  redis-data:
  redis-conf:
  mongodb_master_data:
    driver: local
